server {
    listen 443 ssl;
    server_name chicken-fish.site www.chicken-fish.site;

    ssl_certificate     /etc/letsencrypt/live/chicken-fish.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chicken-fish.site/privkey.pem;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy REST API
    location /api {
        proxy_pass http://atm_gateway_32:80;
        proxy_set_header Host   $host;
        proxy_set_header Cookie $http_cookie;
    }

    # Proxy WebSocket traffic
    location /socket/ {
        proxy_pass            http://atm_gateway_32:80/ws/;
        proxy_http_version    1.1;
        proxy_set_header      Upgrade $http_upgrade;
        proxy_set_header      Connection "Upgrade";
        proxy_set_header      Host $host;
        proxy_set_header      Cookie $http_cookie;
    }
}

server {
    listen 80;
    server_name chicken-fish.site www.chicken-fish.site;
    return 301 https://$host$request_uri;
}
